#!/bin/bash
# initialize_aws.sh v2 run ONCE to create remote state infra
# Reused and extended from previous iteration
#
# What this does:
#   1. Creates an S3 bucket named terraform-state-<account_id>-<region>
#   2. Locks down all public access (state files contain secrets)
#   3. Enables versioning
#   4. Enables AES-256 encryption at rest
#   5. Creates a DynamoDB table for state locking (never two applies at once)
#   6. AUTO-GENERATES environments/dev/backend.tf so you never mistype the values
#
# NEW Features:
#   - checks if bucket/table already exist before creating
#   - validates AWS credentials before doing anything
#   - Generates backend.tf automatically

set -euo pipefail  # exit on error, undefined var, or pipe failure

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [CONFIG] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
# CHANGE THESE TWO LINES PER PROJECT keep the rest default
PROJECT_NAME="crystal-node"   # a.k.a "api-gateway-lab", "networking", "data-platform"
ENVIRONMENT="dev"        # a.k.a "dev", "staging", "prod"

AWS_REGION="us-east-1"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET_NAME="terraform-state-${ACCOUNT_ID}-${AWS_REGION}"  # one bucket reused forever
TABLE_NAME="terraform-state-lock"                           # one table reused forever
STATE_KEY="${PROJECT_NAME}/${ENVIRONMENT}/terraform.tfstate"

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [PREFLIGHT] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Die  AWS creds fail
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "      Bootstrap State Backend     "
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "Account : $ACCOUNT_ID"
echo "Region  : $AWS_REGION"
echo "Bucket  : $BUCKET_NAME"
echo "Table   : $TABLE_NAME"
echo "Key     : $STATE_KEY"
echo ""

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [S3 BUCKET] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Check if bucket already exists, safe to re-run
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null 1>/dev/null; then
  echo "[SKIP] Bucket already exists: $BUCKET_NAME"
else
  echo "[CREATE] S3 bucket: $BUCKET_NAME"
  aws s3api create-bucket \
    --bucket "$BUCKET_NAME" \
    --region "$AWS_REGION"

  # Block ALL public access... state contains resource ARNs, role names, etc.
  # STATE DATA IS CLASSIFIED
  aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
      "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

  # Versioning if state gets corrupted
  # restore the last known-good version from S3 version history
  aws s3api put-bucket-versioning \
    --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled

  # AES-256 server-side encryption at rest
  # For stricter environments, swap SSEAlgorithm to "aws:kms" with a CMK
  aws s3api put-bucket-encryption \
    --bucket "$BUCKET_NAME" \
    --server-side-encryption-configuration '{
      "Rules": [{
        "ApplyServerSideEncryptionByDefault": {
          "SSEAlgorithm": "AES256"
        }
      }]
    }'

  echo "[OK] Bucket configured"
fi

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [DynamoDB LOCK] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Check if table already exists
if aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$AWS_REGION" 2>/dev/null 1>/dev/null; then
  echo "[SKIP] DynamoDB table already exists: $TABLE_NAME"
else
  echo "[CREATE] DynamoDB table: $TABLE_NAME"

  # LockID is the required partition key to lock the state
  # PAY_PER_REQUEST = no provisioned capacity needed, essentially free*
  aws dynamodb create-table \
    --table-name "$TABLE_NAME" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$AWS_REGION"

  echo "[OK] DynamoDB table created"
fi

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [GENERATE BACKEND.tf] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
# writes the backend config directly into the dev environment
BACKEND_FILE="../environments/dev/backend.tf"

cat > "$BACKEND_FILE" <<EOF
# backend.tf | AUTO-GENERATED by bootstrap/initialize_aws.sh <3
# Do NOT edit by hand Re-run initialize_aws.sh to regenerate.
terraform {
  backend "s3" {
    bucket         = "${BUCKET_NAME}"
    key            = "${STATE_KEY}"
    region         = "${AWS_REGION}"
    dynamodb_table = "${TABLE_NAME}"
    encrypt        = true
  }
}
EOF

echo "[OK] Generated: $BACKEND_FILE"

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= [COMPLETE] -=-=-=-=-=-=-=-=-=-=-=-=-=-=
echo ""
echo "(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)(^.^)"
echo ""
echo " [COMPLETE] State backend is ready"
echo ""
echo " bucket         = \"$BUCKET_NAME\""
echo " key            = \"$STATE_KEY\""
echo " region         = \"$AWS_REGION\""
echo " dynamodb_table = \"$TABLE_NAME\""
echo ""
echo " [NEXT]: cd ../environments/dev && terraform init"
echo ""