apiVersion: apps/v1
kind: Deployment
metadata:
  name: crystal-app
  namespace: crystal-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crystal-app
  template:
    metadata:
      labels:
        app: crystal-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: crystal-app
<<<<<<< HEAD:k8s/app.yaml
        image: 463470958137.dkr.ecr.us-east-1.amazonaws.com/crystal-app:bf05dd6df322ca3f5f41fbcb10079fd7be91d02e
=======
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

---
apiVersion: v1
kind: Service
metadata:
  name: crystal-app
  namespace: crystal-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: "crystal-app-nlb"
spec:
  type: LoadBalancer
  selector:
    app: crystal-app
  ports:
  - port: 80
    targetPort: 8080
